---
title: "homework2"
author: "Laha Ale"
date: "February 8, 2019"
output:
  pdf_document: 
    keep_tex: yes
  word_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message = F)
```

## Excerse 6

#### Basic Plot 

```{r ex6_basic}
#*********R CODE START************
library(spBayes)
library(classInt)
library(geoR)
library(MBA)
library(fields) 
library(RColorBrewer)
url <- "https://www.counterpointstat.com/uploads/1/1/9/3/119383887/myscallops.txt"
myscallops <- read.table(url,header = T)

coords <- as.matrix(myscallops[,c("lat","long")])

strata <- myscallops$strata
lgcatch<- myscallops$lgcatch

plot(coords, pch=1, cex=sqrt(strata)/100, col="darkgreen", xlab="Lat", ylab="Long")
leg.vals <- round(quantile(strata),0)
legend("topleft", pch=1, legend=leg.vals, col="darkgreen",
       pt.cex=sqrt(leg.vals)/1000, bty="n", title="strata")

plot(coords, pch=1, cex=sqrt(lgcatch)/2, col="darkgreen", xlab="Lat", ylab="Long")
leg.vals <- round(quantile(lgcatch),0)
legend("topleft", pch=1, legend=leg.vals, col="darkgreen",
       pt.cex=sqrt(leg.vals)/1000, bty="n", title="lgcatch")

```

#### Create a color palette for subsequent plots.
```{r ex6_color}
col.br <- colorRampPalette(c("blue", "cyan", "yellow", "red"))
col.pal <- col.br(5)

fixed <- classIntervals(strata, n = 4, style = "fixed", 
                        fixedBreaks = c(0,6260, 62290, 6310, max(strata) + 1))
fixed.col <- findColours(fixed, col.pal)
plot(coords, col = fixed.col, pch = 19, cex = 0.5, 
     main = "strata classes", xlab = "Lat", ylab = "Long")
legend("topleft", fill = attr(fixed.col, "palette"),
       legend = c("strata1", "strata2", "strata3", "strata4"), 
       bty = "n")
```

#### Surface
```{r Surface}
## MBA and fields libraries for creating surface interpolation plots
x.res <- 148
y.res <- 148
surf <- mba.surf(cbind(coords, strata), 
                 no.X = x.res, no.Y = y.res, 
                 h = 5, m = 2, extend = FALSE)$xyz.est
image.plot(surf, xaxs = "r", 
           yaxs = "r", xlab = "lat", 
           ylab = "long", col = col.br(25))
contour(surf, add=T) 



```

#### 3D Plot
```{r ex6_3d, eval=F}

library(rgl)
col <- rbind(0, cbind(matrix(drape.color(surf[[3]],
                                         col = col.br(25)), x.res - 1, y.res-1), 0))
surface3d(surf[[1]], surf[[2]], surf[[3]], col = abs(col))
axes3d()

title3d(main = "strata", xlab = "Lat", ylab = "Long", zlab = "Strata")
drape.plot(surf[[1]], surf[[2]], surf[[3]],
           col = col.br(150), theta = 225, phi = 50,
           border = FALSE, add.legend = FALSE,
           xlab = "Lat", ylab = "Long", zlab = "Strata")
image.plot(zlim = range(surf[[3]], na.rm = TRUE),
           legend.only = TRUE, horizontal = FALSE)
```
```{r ex6_3dd, echo=F}
library(OpenImageR)
image = readImage("3d.png")
imageShow(image)
```



### (a)

```{r ex_a}
#*********R CODE START************
summary(myscallops)
```

### (b)

```{r ex_b}
#*********R CODE START************


max.dist <- 0.25 * max(iDist(coords))
bins <- 50
vario.strata <- variog(coords = coords,
                       data = myscallops$strata,
                       uvec = (seq(0, max.dist, length = bins)))
plot(vario.strata,type="o")
```

### (c)

```{r ex_c}
#*********R CODE START************
fit.strata<- variofit(vario.strata,cov.model="exponential",fix.nugget=FALSE, nugget=18)
fit.strata
```
As we can see above\$nugget=tausq=0$ \
$sill=tausq+sigmasq=3439272.97$\
$range=3813.02$


## Excerse 7
```{r ex7}
#*********R CODE START************
url_coal <- "https://www.counterpointstat.com/uploads/1/1/9/3/119383887/coal.ash.txt"
coalash <- read.table(url_coal,header = T)
```
### (a)

```{r ex7_a}
#*********R CODE START************
coords_coal <- as.matrix(coalash[,c("x","y")])
coal <- coalash$coal
x.res <- 208
y.res <- 208
surf <- mba.surf(cbind(coords_coal, coal),
                 no.X = x.res, no.Y = y.res, 
                 h = 5, m = 2, extend = FALSE)$xyz.est
image.plot(surf, xaxs = "r", yaxs = "r", xlab = "x", ylab = "y")
contour(surf, add=T) 
```

### (b)

```{r ex7_b}
#*********R CODE START************
library(ggplot2)
coal <- coalash$coal
qplot(coal, geom="histogram") 
stem(coal)
summary(coalash)
```

### (c)

```{r ex7_c}
#*********R CODE START************
vario.coal <- variog(coords = coords_coal,
                     data = coal, uvec = (seq(0, length = bins)))
plot(vario.coal,type="o")
```

### (d)

```{r ex7_d}
#*********R CODE START************
fit.coal<- variofit(vario.coal,
                    cov.model="exponential",
                    fix.nugget=FALSE,
                    max.dist = 1/17, nugget=1.2)
fit.coal
```
As we can see above, the sill corresponded to round 17 is around 2.24, which is match to the plot in (b).
